version: 2
jobs:
  test-job:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: sudo npm install -g @angular/cli
      # Cache to enable faster future jobs
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run tests
      - run: ng test --watch=false --browsers ChromeHeadless
  deploy-job:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: sudo npm install -g @angular/cli
      - run: sudo npm install -g firebase-tools
      - run: npm install
      - run: ng build --prod
      - run: firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2

  -test_and_deploy:
    jobs:
      - test-job
      - deploy-job:
          requires:
            - test-job
          filters:
            branches:
              only: master